import streamlit as st
import requests

API_BASE = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="Customer Decision Assistant",
    layout="centered"
)

# -----------------------------
# Header
# -----------------------------
st.markdown(
    """
    <h2 style="margin-bottom:0;">Customer Decision Intelligence</h2>
    <p style="margin-top:4px; color:#9aa0a6;">
    Revenue-aware, risk-balanced next-best-action recommendations.
    </p>
    """,
    unsafe_allow_html=True
)

st.divider()

# -----------------------------
# Customer Input
# -----------------------------
st.subheader("🔍 Select Customer")

customer_id = st.number_input(
    "Customer ID",
    min_value=1,
    step=1,
    help="Enter a customer identifier to evaluate the next best action."
)

run = st.button("Get Recommendation", use_container_width=True)

# -----------------------------
# Main Flow
# -----------------------------
if run:
    with st.spinner("Analyzing customer context and risks..."):
        response = requests.get(
            f"{API_BASE}/next-best-action/{int(customer_id)}"
        )

    if response.status_code != 200:
        st.error("Unable to generate recommendation. Please try again.")
        st.stop()

    decision = response.json()

    st.divider()

    # -----------------------------
    # Decision Summary
    # -----------------------------
    st.subheader("🎯 Recommended Action")

    action = decision["action"]

    if action == "NO_ACTION":
        st.warning(
            "🚫 **No action recommended at this time**\n\n"
            "Reaching out to this customer now could increase disengagement or churn."
        )
    elif action == "UPSELL":
        st.success(
            "⬆️ **Upsell Recommended**\n\n"
            "This customer is a good candidate for a premium or higher-value offering."
        )
    elif action == "CROSS_SELL":
        st.success(
            "🔁 **Cross-sell Recommended**\n\n"
            "This customer is likely to benefit from a complementary product."
        )

    # -----------------------------
    # Confidence Indicator
    # -----------------------------
    utility = decision.get("expected_utility", 0.0)

    if utility >= 0.2:
        confidence = "High"
    elif utility >= 0.05:
        confidence = "Medium"
    else:
        confidence = "Low"

    st.metric(
        label="Decision Confidence",
        value=confidence
    )

    st.divider()

    # -----------------------------
    # Business Explanation (LLM)
    # -----------------------------
    st.subheader("🗣️ Why this decision was made")

    with st.spinner("Preparing explanation..."):
        explain_resp = requests.post(
            f"{API_BASE}/explain-decision",
            json=decision
        )

    if explain_resp.status_code == 200:
        explanation_text = explain_resp.json()["explanation"]
        st.info(explanation_text)
    else:
        st.info(
            "This decision was made by evaluating customer engagement, "
            "long-term value, and operational risk to ensure safe and responsible outreach."
        )

    st.divider()

    # -----------------------------
    # Historical Context (High Level)
    # -----------------------------
    similar = decision.get("explanation", {}).get("similar_cases", [])

    if similar:
        st.subheader("📚 What happened with similar customers")

        actions = [s["action"] for s in similar]
        summary = {
            "UPSELL": actions.count("UPSELL"),
            "CROSS_SELL": actions.count("CROSS_SELL"),
            "NO_ACTION": actions.count("NO_ACTION"),
        }

        st.write(
            f"- **Upsell attempted**: {summary['UPSELL']} cases\n"
            f"- **Cross-sell attempted**: {summary['CROSS_SELL']} cases\n"
            f"- **No action taken**: {summary['NO_ACTION']} cases\n\n"
            "This historical context helps guide safe and effective decisions."
        )

    else:
        st.caption(
            "No comparable historical cases were found for this customer."
        )

# -----------------------------
# Footer
# -----------------------------
st.divider()
st.caption(
    "Decisions are generated by an AI system designed to prioritize customer trust, "
    "long-term value, and responsible growth."
)